# Generated by Django 5.2.8 on 2025-11-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(choices=[("buy", "buy"), ("sell", "sell")]),
        ),
    ]
